### ISSUE TITLE
Update READMEs, templates, etc... from Pivotal to VMware

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#682]
Mentions of Pivotal sponsorship in the codebase / documentation / READMEs / public facing tooling like github issue templates must now reflect the fact that that role has been taken over by VMware.

initial change (**WITH START DATE MISTAKE**):
 - [x] core: reactor/reactor-core#2722 and reactor/reactor-core#2725
 - [x] pool: reactor/reactor-pool#141
 - [x] addons: reactor/reactor-addons#258
 - [x] netty (reactor/reactor-netty#1691, reactor/reactor-netty#1688, reactor/reactor-netty#1689, reactor/reactor-netty#1690, reactor/reactor-netty#1687)
 - [x] rabbitmq: reactor/reactor-rabbitmq#161

these were not merged before the mistake was found, so they include correct start years:
 - [x] kafka: reactor/reactor-kafka#223 (updated to keep start dates: ✅) and reactor/reactor-kafka#226
 - [x] kotlin: reactor/reactor-kotlin-extensions#27 (updated to keep start dates: ✅)

fixup PRs for the date range:
 - [x] core https://github.com/reactor/reactor-core/pull/2732 
   - [x] which includes https://github.com/reactor/reactor-core/pull/2733
   - [x] merge follow-up in main: https://github.com/reactor/reactor-core/pull/2734
 - [x] pool: refine start years from spotless and manual analysis of git history: https://github.com/reactor/reactor-pool/pull/144
 - [x] addons https://github.com/reactor/reactor-addons/pull/259
 - [x] netty ✅ previous PRs didn't change the start dates
 - [x] rabbitmq reactor/reactor-rabbitmq#162

additional projects:
 - [x] bot: reactor/bot#19
 - [x] site: reactor/projectreactor.io#68
 - [x] BOM: reactor/reactor#702

**Comment by simonbasle** [comment]
for copyright headers, here is the guidance. each header step can be its own commit for a better reviewability:

### Change the copyright to VMware and the end year of the range

1. search-and-replace on all files with regexp
   - from `([0-9]+)-[0-9]+ Pivotal Software Inc, All Rights Reserved` (eg. 2017-2019)
   - to `$1-2021 VMware Inc. or its affiliates, All Rights Reserved` (eg. 2017-2021)
2. search-and-replace on all files with regexp
    - from `([0-9]+)-Present Pivotal Software Inc, All Rights Reserved` (eg. 2017-Present)
    - to `$1-2021 VMware Inc. or its affiliates, All Rights Reserved` (eg. 2017-2021)

### Harmonize URL indentation in license header
Do a search-and-replace on all files with regexp
    - `([ ]?[^ ])[ ]+https://www.apache.org` (matching both `# ` and ` * ` kind of comment blocks)
    - `$1   https://www.apache.org` (harmonizing on 3 spaces: one for the comment block and 2 for indentation of the url, as in the ASF example)
    - then rollback some of the files that are obviously not reactor's (the LICENSE file at root, some Gradle files for instance...)

### Find and remove duplicated copyright headers

via terminal:
```bash
for file in ./**/*; do if [ "$(grep -s -c "Copyright" "${file}")" -gt 1 ]; then echo "${file}"; fi; done
```
### (to be confirmed) Replace all the start year with each project inception year

then the fourth commit was made to replace all the start dates with the same date (project inception). For example if the project in repo was created in 2011:

Regexp search-and-replace:
 - from `20[12][^1]-2021 VMware Inc` (make sure there is no occurrence of 2021 as a start year)
 - to `2011-2021 VMware Inc`

Start year of each project:
 - Reactor-core was started in 2011, and arguably build files in `reactor/reactor` would be too
 - Reactor-Addons: 2016
 - Reactor-Pool: 2018
 - Reactor-Netty: 2016
 - Reactor-Kafka: 2016
 - Reactor-Rabbitmq: 2017
 - Reactor-Kotlin-Extensions: 2019
 - Reactor (BOM): 2011

**Comment by simonbasle** [comment]
this has now been released in the August 2021 release (Dysprosium-SR22, 2020.0.10)
