### ISSUE TITLE
Branch Dysprosium off all projects and use -SNAPSHOT qualifier

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#683]
As we ramp up towards Europium effort, all projects should have their master dedicated to their Europium version and the Dysprosium version be branched off.
Furthermore, we are switching from using `.BUILD-SNAPSHOT` qualifier for snapshots to simply `-SNAPSHOT`, which necessitate a few minor build adjustments.

 - [x] branch reactor Core 3.3.x
   - [x] master is 3.4 + adapt build (reactor/reactor-core#2140)
 - [x] branch reactor addons 3.3.x
   - [x] master is 3.4 + adapt build (reactor/reactor-addons#232)
 - [x] branch reactor pool 0.1.x
   - [x] master is 0.2 + adapt build (reactor/reactor-pool#75)
 - [x] branch reactor netty 0.9.x (done a while ago)
   - [x] adapt build netty in master/1.0 (reactor/reactor-netty#1084)
 - [x] branch reactor kafka 1.2.x
   - [x] master is 1.3 + adapt build (reactor/reactor-kafka#141)
 - [x] branch reactor rabbitmq 1.4.x
   - [x] master is 1.5 + adapt build (reactor/reactor-rabbitmq#133)
 - [x] branch reactor kotlin 1.0.x
   - [x] master is 1.1 extensions + adapt build ? (reactor/reactor-kotlin-extensions#9)
 - [x] branch reactor bom Dysprosium
   - [x] master is 2020.0 - Europium + adapt build (#684)

**Comment by simonbasle** [comment]
Done as of 0cb17d5
